"use client";

import Link from "next/link";
import { ArrowLeft, FileText } from "lucide-react";

export default function Terms() {
    return (
        <div className="min-h-screen bg-black text-white font-sans aurora-bg selection:bg-purple-500/30 p-6 md:p-12">
            <div className="max-w-4xl mx-auto">
                <Link href="/" className="inline-flex items-center gap-2 text-zinc-400 hover:text-white transition-colors mb-8 group">
                    <ArrowLeft className="w-4 h-4 group-hover:-translate-x-1 transition-transform" />
                    Back to Home
                </Link>

                <div className="mb-12">
                    <div className="w-12 h-12 rounded-full bg-green-500/20 flex items-center justify-center mb-6 text-green-300">
                        <FileText className="w-6 h-6" />
                    </div>
                    <h1 className="text-4xl md:text-5xl font-bold tracking-tight mb-6 bg-clip-text text-transparent bg-gradient-to-br from-white via-white to-green-200">
                        Terms of Service
                    </h1>
                    <p className="text-zinc-400">Last Updated: January 21, 2026</p>
                </div>

                <div className="space-y-12 text-zinc-300 leading-relaxed">
                    <section>
                        <h2 className="text-2xl font-bold text-white mb-4">1. Acceptance of Terms</h2>
                        <p>
                            By using Weekend Traveller, you agree to these Terms of Service. If you do not agree, please do not use our application.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-bold text-white mb-4">2. AI-Generated Content</h2>
                        <p>
                            Our travel itineraries are generated by Artificial Intelligence. While we strive for accuracy, travel details (prices, opening hours, availability) can change. We recommend verifying critical details before booking your trip. Weekend Traveller is not responsible for any inaccuracies in the generated plans.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-bold text-white mb-4">3. User Conduct</h2>
                        <p>
                            You agree not to misuse the platform, including sending abusive prompts or attempting to reverse-engineer our services.
                        </p>
                    </section>
                </div>
            </div>
        </div>
    );
}
